'use strict';

const GAME_WIDTH = 1600;
const GAME_HEIGHT = 900;
const BACKGROUND_COLOR = 'black';
const LINE_DISTANCE = 50;
const PATH_SIZE = 75;
const PATH_INSIDE_COLOR = 'white';
const SIMULATION_RATE = 30;
const FAST_ENEMY_COLOR = '#19d4ab';
const BASIC_ENEMY_COLOR = '#2d2e2e';
const STRONG_ENEMY_COLOR = '#73020f';
const PATH_ENDS_COLOR = '#d40018';
const PATH_ENDS_SIZE = 70;
const SPOT_COLOR = '33';
const SPOT_SIZE = 65;
const CONTROLS = {
   i: 'zoomin',
   o: 'zoomout',
};
const TOWER_ROTATE_SPEED = 5;
const TOWER_DISPLAY_WIDTH = 350;
const TOWER_DISPLAY_HEIGHT = 200;
const ENEMY_STATS_WIDTH = 150;
const ENEMY_STATS_HEIGHT = 100;

module.exports = {
   GAME_WIDTH,
   GAME_HEIGHT,
   BACKGROUND_COLOR,
   LINE_DISTANCE,
   PATH_SIZE,
   SIMULATION_RATE,
   FAST_ENEMY_COLOR,
   BASIC_ENEMY_COLOR,
   PATH_INSIDE_COLOR,
   STRONG_ENEMY_COLOR,
   PATH_ENDS_COLOR,
   PATH_ENDS_SIZE,
   SPOT_COLOR,
   SPOT_SIZE,
   CONTROLS,
   TOWER_ROTATE_SPEED,
   TOWER_DISPLAY_WIDTH,
   TOWER_DISPLAY_HEIGHT,
   ENEMY_STATS_WIDTH,
   ENEMY_STATS_HEIGHT,
};
