'use strict';

const GAME_WIDTH = 1600;
const GAME_HEIGHT = 900;
const BACKGROUND_COLOR = 'black';
const LINE_DISTANCE = 50;
const PATH_SIZE = 60;
const PATH_INSIDE_COLOR = 'white';
const SIMULATION_RATE = 30;
const FAST_ENEMY_COLOR = '#19d4ab';
const BASIC_ENEMY_COLOR = '#2d2e2e';
const SPAWNER_COLOR = '#470703';
const SPAWNER_SIZE = 70;

module.exports = {
   GAME_WIDTH,
   GAME_HEIGHT,
   BACKGROUND_COLOR,
   LINE_DISTANCE,
   PATH_SIZE,
   SIMULATION_RATE,
   FAST_ENEMY_COLOR,
   BASIC_ENEMY_COLOR,
   PATH_INSIDE_COLOR,
   SPAWNER_COLOR,
   SPAWNER_SIZE,
};
